package com.boxpix.app.data.vault

import android.media.MediaDataSource
import android.media.MediaMetadataRetriever
import com.boxpix.app.data.media.VideoFrameExtractor
import com.boxpix.app.data.media.VideoPoster
import kotlinx.coroutines.runBlocking

/**
 * Poster frames for VAULT videos, generated by the phone itself: the worker
 * never enters the vault (owner's decision), so the extraction runs on-demand
 * here — a MediaDataSource whose reads are chunk-aligned decrypting range
 * requests, no full download, nothing cleartext on disk.
 *
 * Abstracted as a fun interface so the vault thumbnail logic stays JVM-testable
 * (MediaMetadataRetriever is device-only).
 */
fun interface VaultFrameExtractor {
    fun extract(handle: VaultFileHandle): VideoFrameExtractor.Extraction?
}

class AndroidVaultFrameExtractor : VaultFrameExtractor {

    override fun extract(handle: VaultFileHandle): VideoFrameExtractor.Extraction? {
        val retriever = MediaMetadataRetriever()
        return try {
            retriever.setDataSource(VaultMediaDataSource(handle))
            val durationSeconds = retriever
                .extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)
                ?.toLongOrNull()?.div(1000)
            val frame = retriever.getFrameAtTime(1_000_000, MediaMetadataRetriever.OPTION_CLOSEST_SYNC)
                ?: retriever.getFrameAtTime(-1)
                ?: return null
            VideoFrameExtractor.Extraction(VideoPoster.toWebpThumb(frame), durationSeconds)
        } catch (_: Exception) {
            null
        } finally {
            runCatching { retriever.release() }
        }
    }

    /** The retriever calls readAt from its own thread — runBlocking is safe. */
    private class VaultMediaDataSource(private val handle: VaultFileHandle) : MediaDataSource() {
        override fun getSize(): Long = handle.cleartextSize

        override fun readAt(position: Long, buffer: ByteArray, offset: Int, size: Int): Int {
            if (position >= handle.cleartextSize) return -1
            val bytes = try {
                runBlocking { handle.read(position, size) }
            } catch (_: Exception) {
                return -1
            }
            if (bytes.isEmpty()) return -1
            bytes.copyInto(buffer, destinationOffset = offset)
            return bytes.size
        }

        override fun close() = Unit
    }
}
